title: 
logo: https://github.com/AkshitVerma97/Portfolio/blob/4c6bf0d44e966d56d8b0e89833d6f2e860ef1436/assets/images/Adobe%20Express%20-%20file.jpg
description: Akshit Verma
show_downloads: true
theme: jekyll-theme-minimal
